version: '3'

services:
  db:
    image: mongo:5
    container_name: mongo-dragonBall
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: dragonBallDB
    volumes:
      - ./mongo:/data/db